#!/bin/sh

if [ "x${1}" = "x" ];then
  echo "syntax: ${0} <commit-message>"
  exit 1
fi

if [ ! -d "lib" ] || [ ! -d "public.devel" ] || [ ! -f "Gemfile" ] || [ ! -f "config.ru" ];then
  echo "public.devel directory should exist"
  exit 1
fi

rm -rf ./public

sudo git add .
sudo git commit -a -m $1
sudo git pull bb master

cd public.devel && ./deploy.sh
sudo service nginx reload
